import React, { useMemo, useState } from 'react';
import { Search, SlidersHorizontal, X } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { Category, FabricType, OccasionType, SizeOption } from '../../types';
import { ProductCard } from '../common/ProductCard';
import { useBodyScrollLock } from '../../hooks/useBodyScrollLock';

const sizes: SizeOption[] = ['Unstitched', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'Custom Made-to-Measure'];
const fabrics: FabricType[] = ['Pure Mulberry Silk', 'Kanjeevaram Silk', 'Banarasi Katan Silk', 'Organza Silk', 'Raw Silk', 'Chanderi', 'Georgette', 'Velvet', 'Tussar Silk', 'Chikankari Cotton'];
const occasions: OccasionType[] = ['Bridal Trousseau', 'Wedding Guest', 'Festive & Puja', 'Reception & Party', 'Sangeet & Mehendi', 'Cocktail & Evening'];
const pageSize = 12;

export const ProductListingPage: React.FC = () => {
  const { filters, products, navigate, resetFilters, setFilters } = useStore();
  const [isFiltersOpen, setIsFiltersOpen] = useState(false);
  useBodyScrollLock(isFiltersOpen);
  const [visibleCount, setVisibleCount] = useState(pageSize);
  const categories = useMemo<Category[]>(() => ['All', ...Array.from(new Set(products.map((product) => product.category))).filter(Boolean).sort()], [products]);
  const availableColors = useMemo(() => Array.from(new Set(products.flatMap((product) => product.colors.map((color) => color.colorName)))).slice(0, 12), [products]);
  const matchingProducts = useMemo(() => products.filter((product) => {
    if (filters.category !== 'All' && product.category !== filters.category) return false;
    if (filters.fabrics.length && !filters.fabrics.includes(product.fabric)) return false;
    if (filters.occasions.length && !filters.occasions.includes(product.occasion)) return false;
    if (filters.sizes.length && !product.availableSizes.some((size) => filters.sizes.includes(size))) return false;
    if (filters.colors.length && !product.colors.some((color) => filters.colors.includes(color.colorName))) return false;
    if (filters.readyToShipOnly && (!product.isReadyToShip || product.stockCount <= 0)) return false;
    if (filters.handloomOnly && !product.isHandloomCertified) return false;
    if (product.priceINR < filters.minPriceINR || product.priceINR > filters.maxPriceINR) return false;
    const query = filters.searchQuery.trim().toLowerCase();
    return !query || [product.title, product.category, product.fabric, product.occasion, product.sku, ...product.tags].some((value) => value.toLowerCase().includes(query));
  }).sort((a, b) => {
    if (filters.sortBy === 'newest') return Number(Boolean(b.isNewArrival)) - Number(Boolean(a.isNewArrival));
    if (filters.sortBy === 'price-low-high') return a.priceINR - b.priceINR;
    if (filters.sortBy === 'price-high-low') return b.priceINR - a.priceINR;
    if (filters.sortBy === 'rating') return b.rating - a.rating;
    if (filters.sortBy === 'name-a-z') return a.title.localeCompare(b.title);
    return Number(Boolean(b.isBestseller)) - Number(Boolean(a.isBestseller));
  }), [filters, products]);
  const toggle = <T,>(key: 'fabrics' | 'occasions' | 'sizes' | 'colors', value: T) => { setVisibleCount(pageSize); setFilters((current) => ({ ...current, [key]: (current[key] as T[]).includes(value) ? (current[key] as T[]).filter((item) => item !== value) : [...(current[key] as T[]), value] })); };
  const updateFilters = (next: Partial<typeof filters>) => { setVisibleCount(pageSize); setFilters((current) => ({ ...current, ...next })); };

  return <div className="min-h-screen bg-[#fffdf9] py-8 sm:py-12"><div className="mx-auto max-w-[1440px] px-4 sm:px-7">
    <header className="border-b border-[#ddd7cf] pb-7"><button onClick={() => navigate('home')} className="text-[10px] uppercase tracking-[.15em] text-stone-500 hover:underline">Home / {filters.category === 'All' ? 'Shop' : filters.category}</button><div className="mt-4 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-stone-500">AB Collection</p><h1 className="mt-2 font-serif text-4xl sm:text-5xl">{filters.category === 'All' ? 'The collection' : filters.category}</h1><p className="mt-2 text-sm text-stone-600">{matchingProducts.length} products in the current catalog.</p></div><div className="flex flex-wrap gap-2"><label className="relative min-w-[220px]"><span className="sr-only">Search AB Collection</span><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" /><input value={filters.searchQuery} onChange={(event) => updateFilters({ searchQuery: event.target.value })} placeholder="Search styles, fabric or SKU" className="w-full border border-[#ddd7cf] bg-white py-2.5 pl-9 pr-3 text-xs" /></label><button onClick={() => setIsFiltersOpen(true)} className="inline-flex items-center gap-2 border border-[#2c2926] px-4 py-2.5 text-[11px] font-semibold uppercase tracking-[.12em] lg:hidden"><SlidersHorizontal className="h-4 w-4" />Filter</button><select value={filters.sortBy} onChange={(event) => updateFilters({ sortBy: event.target.value as typeof filters.sortBy })} className="border border-[#ddd7cf] bg-white px-3 py-2.5 text-xs"><option value="featured">Recommended</option><option value="newest">Newest</option><option value="price-low-high">Price: low to high</option><option value="price-high-low">Price: high to low</option><option value="name-a-z">Name: A–Z</option><option value="rating">Highest rated</option></select></div></div></header>
    <div className="mt-8 grid gap-8 lg:grid-cols-[250px_minmax(0,1fr)]"><aside className="hidden lg:block"><FilterPanel filters={filters} categories={categories} sizes={sizes} fabrics={fabrics} occasions={occasions} colors={availableColors} onReset={resetFilters} onUpdate={updateFilters} onToggle={toggle} /></aside><main className="min-w-0"><div className="mb-5 flex items-center justify-between"><p className="text-xs text-stone-500">{matchingProducts.length} pieces</p>{hasFilters(filters) && <button onClick={resetFilters} className="text-[11px] font-semibold uppercase tracking-[.12em] underline underline-offset-4">Clear filters</button>}</div>{!products.length ? <CatalogSkeleton /> : matchingProducts.length ? <><div className="grid grid-cols-2 gap-x-4 gap-y-9 sm:grid-cols-3 sm:gap-x-6 xl:grid-cols-4">{matchingProducts.slice(0, visibleCount).map((product) => <ProductCard key={product.id} product={product} />)}</div>{visibleCount < matchingProducts.length && <div className="mt-12 text-center"><button onClick={() => setVisibleCount((count) => count + pageSize)} className="border border-[#2c2926] px-6 py-3 text-[11px] font-semibold uppercase tracking-[.13em] transition hover:bg-[#2c2926] hover:text-white">Load more pieces</button></div>}</> : <div className="border border-dashed border-[#cfc6bd] bg-[#f7f5f2] px-6 py-20 text-center"><p className="font-serif text-3xl">No pieces found</p><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-stone-600">Try broadening your filters or explore a different collection.</p><button onClick={resetFilters} className="mt-6 border border-[#2c2926] px-5 py-3 text-[11px] font-semibold uppercase tracking-[.12em]">Clear filters</button></div>}</main></div>
  </div>{isFiltersOpen && <div className="fixed inset-0 z-50 bg-black/35 lg:hidden" onClick={() => setIsFiltersOpen(false)}><aside onClick={(event) => event.stopPropagation()} className="absolute inset-x-0 bottom-0 max-h-[85vh] overflow-y-auto overscroll-contain bg-[#fffdf9] p-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-serif text-2xl">Filter the boutique</h2><button onClick={() => setIsFiltersOpen(false)} aria-label="Close filters"><X className="h-5 w-5" /></button></div><FilterPanel filters={filters} categories={categories} sizes={sizes} fabrics={fabrics} occasions={occasions} colors={availableColors} onReset={resetFilters} onUpdate={updateFilters} onToggle={toggle} /><button onClick={() => setIsFiltersOpen(false)} className="mt-5 w-full bg-[#2c2926] py-3 text-[11px] font-semibold uppercase tracking-[.12em] text-white">Show {matchingProducts.length} pieces</button></aside></div>}</div>;
};

type FilterPanelProps = { filters: ReturnType<typeof useStore>['filters']; categories: Category[]; sizes: SizeOption[]; fabrics: FabricType[]; occasions: OccasionType[]; colors: string[]; onReset: () => void; onUpdate: (next: Partial<ReturnType<typeof useStore>['filters']>) => void; onToggle: <T>(key: 'fabrics' | 'occasions' | 'sizes' | 'colors', value: T) => void; };
const FilterPanel: React.FC<FilterPanelProps> = ({ filters, categories, sizes, fabrics, occasions, colors, onReset, onToggle, onUpdate }) => <div className="border border-[#ddd7cf] bg-white p-5"><div className="flex items-center justify-between border-b border-[#eee8e2] pb-4"><h2 className="font-serif text-xl">Filters</h2><button onClick={onReset} className="text-[10px] font-semibold uppercase tracking-[.12em] underline">Reset</button></div><FilterGroup title="Category">{categories.map((category) => <label key={category} className="flex items-center gap-2 py-1.5 text-xs"><input type="radio" name="category" checked={filters.category === category} onChange={() => onUpdate({ category })} />{category}</label>)}</FilterGroup><FilterGroup title="Availability"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={filters.readyToShipOnly} onChange={(event) => onUpdate({ readyToShipOnly: event.target.checked })} />Ready to ship</label><label className="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={filters.handloomOnly} onChange={(event) => onUpdate({ handloomOnly: event.target.checked })} />Handloom certified</label></FilterGroup><FilterGroup title="Price"><div className="grid grid-cols-2 gap-2"><label className="text-[10px] uppercase tracking-wider text-stone-500">From<input type="number" value={filters.minPriceINR} min="0" onChange={(event) => onUpdate({ minPriceINR: Number(event.target.value) || 0 })} className="mt-1 w-full border border-[#ddd7cf] p-2 text-xs text-stone-800" /></label><label className="text-[10px] uppercase tracking-wider text-stone-500">To<input type="number" value={filters.maxPriceINR} min="0" onChange={(event) => onUpdate({ maxPriceINR: Number(event.target.value) || 0 })} className="mt-1 w-full border border-[#ddd7cf] p-2 text-xs text-stone-800" /></label></div></FilterGroup><FilterCheckGroup title="Fabric" values={fabrics} active={filters.fabrics} onToggle={(value) => onToggle('fabrics', value)} /><FilterCheckGroup title="Occasion" values={occasions} active={filters.occasions} onToggle={(value) => onToggle('occasions', value)} /><FilterCheckGroup title="Size" values={sizes} active={filters.sizes} onToggle={(value) => onToggle('sizes', value)} /><FilterCheckGroup title="Colour" values={colors} active={filters.colors} onToggle={(value) => onToggle('colors', value)} /></div>;
const FilterGroup = ({ title, children }: { title: string; children: React.ReactNode }) => <fieldset className="border-b border-[#eee8e2] py-5 last:border-0"><legend className="mb-3 text-[10px] font-semibold uppercase tracking-[.14em] text-stone-500">{title}</legend>{children}</fieldset>;
const FilterCheckGroup = <T extends string>({ title, values, active, onToggle }: { title: string; values: T[]; active: T[]; onToggle: (value: T) => void }) => <FilterGroup title={title}><div className="max-h-40 space-y-1 overflow-y-auto">{values.map((value) => <label key={value} className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={active.includes(value)} onChange={() => onToggle(value)} />{value}</label>)}</div></FilterGroup>;
const CatalogSkeleton = () => <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <div key={index} className="animate-pulse"><div className="aspect-[3/4] bg-[#eee9e2]" /><div className="mt-3 h-3 w-3/4 bg-[#eee9e2]" /><div className="mt-2 h-3 w-1/2 bg-[#eee9e2]" /></div>)}</div>;
const hasFilters = (filters: ReturnType<typeof useStore>['filters']) => filters.category !== 'All' || filters.fabrics.length > 0 || filters.occasions.length > 0 || filters.sizes.length > 0 || filters.colors.length > 0 || filters.readyToShipOnly || filters.handloomOnly || Boolean(filters.searchQuery) || filters.minPriceINR > 0 || filters.maxPriceINR < 150000;
