import React, { useMemo, useState } from 'react';
import { useStore } from '../../context/StoreContext';
import { Category, Order, OrderStatus, Product } from '../../types';
import { Boxes, ChevronRight, CircleDollarSign, ClipboardList, LayoutDashboard, Package, Plus, Search, Settings, ShieldCheck, TicketPercent, Users, X } from 'lucide-react';

type AdminTab = 'dashboard' | 'products' | 'orders' | 'customers' | 'inventory' | 'coupons' | 'settings';
const STATUSES: OrderStatus[] = ['Order Placed', 'Artisan Tailoring', 'Quality Inspection', 'Dispatched', 'In Transit', 'Out for Delivery', 'Delivered', 'Cancelled'];

export const AdminPortalPage: React.FC = () => {
  const { products, orders, coupons, customer, formatPrice, updateOrderStatus, addProduct, navigate } = useStore();
  const [activeTab, setActiveTab] = useState<AdminTab>('dashboard');
  const [query, setQuery] = useState('');
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<Category>('');
  const [price, setPrice] = useState(12500);
  const [stock, setStock] = useState(8);
  const revenue = orders.reduce((sum, order) => sum + order.totalINR, 0);
  const filteredProducts = useMemo(() => products.filter((product) => `${product.title} ${product.sku} ${product.category}`.toLowerCase().includes(query.toLowerCase())), [products, query]);
  const categoryOptions = useMemo(() => Array.from(new Set(products.map((product) => product.category))).filter(Boolean).sort(), [products]);
  const filteredOrders = useMemo(() => orders.filter((order) => `${order.orderNumber} ${order.shippingAddress.fullName} ${order.orderStatus}`.toLowerCase().includes(query.toLowerCase())), [orders, query]);
  const nav = [["dashboard", "Dashboard", LayoutDashboard], ["products", "Products", Package], ["orders", "Orders", ClipboardList], ["customers", "Customers", Users], ["inventory", "Inventory", Boxes], ["coupons", "Coupons", TicketPercent], ["settings", "Settings", Settings]] as const;
  const titleForTab: Record<AdminTab, string> = { dashboard: 'Welcome back, Admin', products: 'Products', orders: 'Orders', customers: 'Customers', inventory: 'Inventory', coupons: 'Coupon Management', settings: 'Settings' };

  const createProduct = (event: React.FormEvent) => {
    event.preventDefault();
    if (!title.trim() || !category.trim()) return;
    const image = 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80';
    addProduct({ id: `mb-custom-${Date.now()}`, title, subtitle: 'New catalog item — complete client-approved details before publication.', sku: `AB-${Math.floor(1000 + Math.random() * 9000)}`, category, fabric: 'Raw Silk', occasion: 'Festive & Puja', priceINR: price, rating: 0, reviewCount: 0, images: [image], colors: [{ colorName: 'Ivory', colorHex: '#E9E3DA', images: [image] }], availableSizes: ['S', 'M', 'L'], stockCount: stock, isReadyToShip: true, isNewArrival: true, description: 'New AB Collection catalog item. Complete product details before external publication.', craftDetails: 'Craft details pending.', careInstructions: 'Professional dry clean only.', includesBlousePiece: false, customStitchingAvailable: false, customStitchingFeeINR: 0, tags: ['new'] });
    setTitle(''); setIsAddOpen(false);
  };

  return <div className="min-h-screen bg-[#f7f5f2] text-[#2c2926]"><div className="mx-auto flex min-h-screen max-w-[1600px]">
    <aside className="hidden w-60 shrink-0 border-r border-[#ddd7cf] bg-[#f1efeb] p-5 lg:flex lg:flex-col"><button onClick={() => navigate('home')} className="border-b border-[#d7d0c8] pb-6 text-left"><span className="block font-serif text-xl">AB Collection Admin</span><span className="mt-1 block text-[10px] uppercase tracking-[.18em] text-stone-500">Store Manager</span></button><nav className="mt-7 space-y-1">{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setActiveTab(id)} className={`flex w-full items-center gap-3 px-3 py-2.5 text-left text-xs font-medium ${activeTab === id ? 'bg-[#625e59] text-white' : 'text-stone-600 hover:bg-white'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav><button onClick={() => navigate('home')} className="mt-auto pt-8 text-left text-xs text-stone-500">← Return to storefront</button></aside>
    <main className="min-w-0 flex-1 p-4 sm:p-7 lg:p-10"><header className="mb-8 flex flex-col gap-4 border-b border-[#ddd7cf] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-stone-500">AB Collection / Admin</p><h1 className="mt-1 font-serif text-3xl">{titleForTab[activeTab]}</h1><p className="mt-1 text-xs text-stone-500">Manage your store operations from one calm workspace.</p></div><button onClick={() => setIsAddOpen(true)} className="inline-flex items-center gap-2 self-start bg-[#625e59] px-4 py-2.5 text-xs font-semibold text-white hover:bg-[#494541] sm:self-auto"><Plus className="h-4 w-4" />Add product</button></header>
      {activeTab === 'dashboard' && <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Recorded order total" value={formatPrice(revenue)} icon={CircleDollarSign} /><Metric label="Active orders" value={String(orders.filter((order) => !['Delivered', 'Cancelled'].includes(order.orderStatus)).length)} icon={ClipboardList} /><Metric label="Products" value={String(products.length)} icon={Package} /><Metric label="Low stock" value={String(products.filter((product) => product.stockCount <= 3).length)} icon={ShieldCheck} warning /></section><section className="mt-7 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><div className="border border-[#ddd7cf] bg-white p-5"><h2 className="font-serif text-xl">Revenue trend</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-stone-500">Trend reporting is not available until a trusted reporting pipeline is configured. This dashboard intentionally does not render sample analytics.</p></div><ActionPanel orders={orders.length} products={products.length} onOrders={() => setActiveTab('orders')} onProducts={() => setActiveTab('products')} /></section><OrderTable orders={orders.slice(0, 5)} formatPrice={formatPrice} onStatusChange={updateOrderStatus} /></>}
      {(activeTab === 'products' || activeTab === 'inventory') && <><Toolbar query={query} setQuery={setQuery} label="Search products or SKU" /><ProductTable products={filteredProducts} formatPrice={formatPrice} /></>}
      {activeTab === 'orders' && <><Toolbar query={query} setQuery={setQuery} label="Search orders or customers" /><OrderTable orders={filteredOrders} formatPrice={formatPrice} onStatusChange={updateOrderStatus} /></>}
      {activeTab === 'customers' && <section className="border border-[#ddd7cf] bg-white"><div className="grid divide-y divide-[#e7e1da] sm:grid-cols-3 sm:divide-x sm:divide-y-0"><MiniStat label="Customer directory" value="—" /><MiniStat label="New customers" value="—" /><MiniStat label="VIP members" value="—" /></div><div className="p-5"><p className="text-sm leading-relaxed text-stone-500">A multi-customer directory requires an admin-only Firestore query or trusted server report. It is deliberately not populated from the signed-in customer profile.</p><div className="mt-6"><TableHeader columns={['Current session', 'Tier', 'Recorded spend', 'Orders', 'Scope']} /><div className="grid grid-cols-5 gap-3 border-b border-[#eee8e1] py-4 text-xs"><span className="font-medium">{customer.fullName}</span><span>{customer.tier}</span><span>{formatPrice(customer.totalSpendINR)}</span><span>{customer.ordersCount}</span><span>Current profile only</span></div></div></div></section>}
      {activeTab === 'coupons' && <section className="border border-[#ddd7cf] bg-white p-5"><div className="grid gap-4 sm:grid-cols-3"><MiniStat label="Active coupons" value={String(coupons.filter((coupon) => coupon.isActive).length)} /><MiniStat label="Configured coupons" value={String(coupons.length)} /><MiniStat label="Expiring soon" value="—" /></div><div className="mt-7"><TableHeader columns={['Code', 'Type', 'Value', 'Minimum spend', 'Expiry']} />{coupons.map((coupon) => <div key={coupon.code} className="grid grid-cols-5 gap-3 border-b border-[#eee8e1] py-4 text-xs"><b>{coupon.code}</b><span>{coupon.discountType}</span><span>{coupon.discountType === 'fixed' ? formatPrice(coupon.discountValue) : `${coupon.discountValue}%`}</span><span>{formatPrice(coupon.minCartValueINR)}</span><span>{coupon.expiryDate}</span></div>)}</div></section>}
      {activeTab === 'settings' && <SettingsPanel />}
    </main></div>
    {isAddOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={createProduct} className="w-full max-w-lg bg-white p-6 shadow-2xl"><div className="flex items-center justify-between border-b border-stone-200 pb-4"><h2 className="font-serif text-2xl">Add New Product</h2><button type="button" onClick={() => setIsAddOpen(false)}><X /></button></div><div className="mt-5 grid gap-4 text-xs"><label>Product title<input required value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 w-full border border-stone-300 p-3" /></label><div className="grid grid-cols-2 gap-4"><label>Category<input required list="catalog-categories" value={category} onChange={(event) => setCategory(event.target.value)} placeholder="Existing or new category" className="mt-1 w-full border border-stone-300 p-3" /><datalist id="catalog-categories">{categoryOptions.map((value) => <option key={value} value={value} />)}</datalist></label><label>Price (INR)<input type="number" value={price} onChange={(event) => setPrice(Number(event.target.value))} className="mt-1 w-full border border-stone-300 p-3" /></label></div><label>Stock<input type="number" min="0" value={stock} onChange={(event) => setStock(Number(event.target.value))} className="mt-1 w-full border border-stone-300 p-3" /></label></div><button className="mt-6 w-full bg-[#625e59] py-3 text-xs font-semibold uppercase tracking-widest text-white">Publish product</button></form></div>}
  </div>;
};

const Metric = ({ label, value, icon: Icon, warning = false }: { label: string; value: string; icon: React.ElementType; warning?: boolean }) => <div className="border border-[#ddd7cf] bg-white p-5"><div className="flex items-center justify-between text-xs text-stone-500"><span>{label}</span><Icon className="h-4 w-4" /></div><div className={`mt-3 font-serif text-3xl ${warning ? 'text-rose-700' : ''}`}>{value}</div></div>;
const MiniStat = ({ label, value }: { label: string; value: string }) => <div className="p-5"><p className="text-[10px] uppercase tracking-[.16em] text-stone-500">{label}</p><p className="mt-2 font-serif text-3xl">{value}</p></div>;
const Toolbar = ({ query, setQuery, label }: { query: string; setQuery: (value: string) => void; label: string }) => <div className="mb-5"><div className="relative max-w-sm"><Search className="absolute left-3 top-3 h-4 w-4 text-stone-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={label} className="w-full border border-[#d8d1c9] bg-white py-2.5 pl-9 pr-3 text-xs" /></div></div>;
const TableHeader = ({ columns }: { columns: string[] }) => <div className="grid grid-cols-5 gap-3 border-b border-[#ddd7cf] pb-3 text-[10px] uppercase tracking-[.14em] text-stone-500">{columns.map((column) => <span key={column}>{column}</span>)}</div>;
const ProductTable = ({ products, formatPrice }: { products: Product[]; formatPrice: (amount: number) => string }) => <section className="overflow-x-auto border border-[#ddd7cf] bg-white p-5"><TableHeader columns={['Product', 'SKU', 'Category', 'Price', 'Stock']} />{products.map((product) => <div key={product.id} className="grid min-w-[720px] grid-cols-5 items-center gap-3 border-b border-[#eee8e1] py-3 text-xs"><div className="flex items-center gap-3"><img src={product.images[0]} alt="" className="h-10 w-8 object-cover" /><b className="truncate">{product.title}</b></div><span>{product.sku}</span><span>{product.category}</span><span>{formatPrice(product.priceINR)}</span><span className={product.stockCount <= 3 ? 'font-semibold text-rose-700' : ''}>{product.stockCount}</span></div>)}</section>;
const OrderTable = ({ orders, formatPrice, onStatusChange }: { orders: Order[]; formatPrice: (amount: number) => string; onStatusChange: (id: string, status: OrderStatus) => void }) => <section className="mt-7 overflow-x-auto border border-[#ddd7cf] bg-white p-5"><p className="mb-4 text-xs text-stone-500">Order-status changes remain disabled until the trusted admin fulfilment service is connected.</p><TableHeader columns={['Order', 'Customer', 'Amount', 'Payment', 'Status']} />{orders.map((order) => <div key={order.id} className="grid min-w-[720px] grid-cols-5 items-center gap-3 border-b border-[#eee8e1] py-3 text-xs"><b>{order.orderNumber}</b><span>{order.shippingAddress.fullName}</span><span>{formatPrice(order.totalINR)}</span><span>{order.paymentStatus}</span><select aria-label={`Order status for ${order.orderNumber}`} value={order.orderStatus} disabled onChange={(event) => onStatusChange(order.id, event.target.value as OrderStatus)} className="cursor-not-allowed border border-stone-200 bg-stone-100 p-1.5 text-xs text-stone-600">{STATUSES.map((status) => <option key={status}>{status}</option>)}</select></div>)}</section>;
const ActionPanel = ({ orders, products, onOrders, onProducts }: { orders: number; products: number; onOrders: () => void; onProducts: () => void }) => <div className="border border-[#ddd7cf] bg-white p-5"><h2 className="font-serif text-xl">Action items</h2><button onClick={onOrders} className="mt-5 flex w-full items-center justify-between border-b border-stone-200 py-3 text-left text-xs">Review orders <span>{orders}</span><ChevronRight className="h-4 w-4" /></button><button onClick={onProducts} className="flex w-full items-center justify-between border-b border-stone-200 py-3 text-left text-xs">Review catalog <span>{products}</span><ChevronRight className="h-4 w-4" /></button></div>;
const SettingsPanel = () => <section className="max-w-3xl border border-[#ddd7cf] bg-white p-6"><h2 className="font-serif text-2xl">Store Information</h2><p className="mt-1 text-xs text-stone-500">Business settings are ready to move to the protected Firestore settings record.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{['Store name', 'Contact email', 'Phone number', 'Store currency'].map((label, index) => <label key={label} className="text-xs text-stone-600">{label}<input defaultValue={index === 0 ? 'AB Collection' : index === 1 ? 'Aadyaboutique2023@gamil.com' : index === 2 ? '9014461462' : 'INR – Indian Rupee'} className="mt-1 w-full border-b border-stone-300 py-2 text-sm outline-none" /></label>)}</div><label className="mt-6 block text-xs text-stone-600">Address<textarea defaultValue="AB Collection / Aadya Boutique, Suvarna Heights, 1049/1 Matrusri Nagar, Miyapur, Hyderabad – 500049" className="mt-1 min-h-28 w-full border border-stone-300 p-3 text-sm" /></label><p className="mt-3 text-xs text-amber-800">Verify the supplied email domain with the client before production: gamil.com was provided.</p><button className="mt-6 bg-[#625e59] px-5 py-3 text-xs font-semibold uppercase tracking-widest text-white">Save changes</button></section>;
