import React, { useState } from 'react';
import { Mail, MapPin, Phone, Send } from 'lucide-react';
import { BRAND } from '../../config/brand';
import { useStore } from '../../context/StoreContext';

export const ContactConciergePage: React.FC = () => {
  const { showToast } = useStore();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); showToast('Message captured', 'This contact form is awaiting an email or CRM connection. Please contact AB Collection directly for now.', 'info'); setName(''); setEmail(''); setMessage(''); };
  return <main className="min-h-screen bg-[#fffdf9] px-4 py-12 sm:px-7 sm:py-16"><div className="mx-auto max-w-6xl"><header className="max-w-2xl"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-stone-500">AB Collection</p><h1 className="mt-3 font-serif text-4xl sm:text-6xl">Contact us</h1><p className="mt-4 text-sm leading-6 text-stone-600">Contact AB Collection for current product, availability, and store assistance.</p></header><div className="mt-10 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><aside className="border border-[#ddd7cf] bg-[#f7f5f2] p-6 sm:p-8"><h2 className="font-serif text-2xl">Visit AB Collection</h2><div className="mt-6 space-y-5 text-sm text-stone-600"><a href={BRAND.mapsUrl} target="_blank" rel="noreferrer" className="flex gap-3 hover:text-stone-950"><MapPin className="mt-0.5 h-5 w-5 shrink-0" /><span>{BRAND.addressLines.map((line) => <React.Fragment key={line}>{line}<br /></React.Fragment>)}</span></a><a href={BRAND.whatsappUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 hover:text-stone-950"><Phone className="h-5 w-5" />WhatsApp: {BRAND.phone}</a><a href={`mailto:${BRAND.email}`} className="flex items-center gap-3 hover:text-stone-950"><Mail className="h-5 w-5" />{BRAND.email}</a></div><a href={BRAND.mapsUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex border border-[#2c2926] px-5 py-3 text-[11px] font-semibold uppercase tracking-[.12em] hover:bg-[#2c2926] hover:text-white">Open in Google Maps</a><p className="mt-7 border-t border-[#ddd7cf] pt-5 text-xs leading-5 text-stone-500">Business hours and social-media links will appear here after the client provides them.</p></aside><section className="border border-[#ddd7cf] bg-white p-6 sm:p-8"><h2 className="font-serif text-2xl">Send a message</h2><p className="mt-2 text-sm text-stone-600">This form is ready for a future email-service connection.</p><form onSubmit={submit} className="mt-6 grid gap-4"><label className="text-xs text-stone-600">Name<input value={name} onChange={(event) => setName(event.target.value)} required className="mt-1.5 w-full border border-[#cfc6bd] p-3 text-sm text-stone-900" /></label><label className="text-xs text-stone-600">Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" required className="mt-1.5 w-full border border-[#cfc6bd] p-3 text-sm text-stone-900" /></label><label className="text-xs text-stone-600">How can we help?<textarea value={message} onChange={(event) => setMessage(event.target.value)} required rows={5} className="mt-1.5 w-full border border-[#cfc6bd] p-3 text-sm text-stone-900" /></label><button className="inline-flex w-fit items-center gap-2 bg-[#2c2926] px-5 py-3 text-[11px] font-semibold uppercase tracking-[.12em] text-white"><Send className="h-4 w-4" />Send message</button></form></section></div></div></main>;
};
