import React from 'react';
import { useStore } from '../../context/StoreContext';
import { AppView } from '../../types';

const pages: Partial<Record<AppView, { eyebrow: string; title: string; lead: string; sections: { title: string; body: string }[] }>> = {
  'shipping-policy': { eyebrow: 'AB Collection information', title: 'Shipping policy', lead: 'This is a placeholder policy page. Final shipping terms, timelines and regions must be approved by AB Collection before publication.', sections: [{ title: 'Order handling', body: 'Order handling and dispatch information will be confirmed by the store after an order is placed.' }, { title: 'Delivery', body: 'Delivery availability, costs and timing depend on the delivery address and the selected product.' }] },
  'returns-policy': { eyebrow: 'AB Collection information', title: 'Returns & exchange', lead: 'This is a placeholder policy page. Final return and exchange terms must be approved by AB Collection before publication.', sections: [{ title: 'Eligibility', body: 'Eligibility will depend on the product type, its condition and whether tailoring or customization has been requested.' }, { title: 'How to request support', body: 'Contact AB Collection with your order details for current support guidance.' }] },
  'cancellation-policy': { eyebrow: 'Boutique information', title: 'Cancellation policy', lead: 'This is placeholder content awaiting the boutique’s final cancellation terms.', sections: [{ title: 'Before dispatch', body: 'Contact the boutique concierge as soon as possible. Cancellation availability may depend on order processing status.' }] },
  'privacy-policy': { eyebrow: 'Boutique information', title: 'Privacy policy', lead: 'This placeholder outlines the need for approved legal copy. Firebase Authentication and Firestore are used for account and customer data in this application.', sections: [{ title: 'Your account data', body: 'Authenticated customer data is isolated by Firebase user ID and protected by Firestore rules.' }, { title: 'Final policy', body: 'A business-approved privacy policy must be provided before public launch.' }] },
  'terms-policy': { eyebrow: 'Boutique information', title: 'Terms & conditions', lead: 'This placeholder must be replaced with business-approved terms before public launch.', sections: [{ title: 'Orders', body: 'Orders are currently created as Cash on Delivery requests with payment status pending.' }] },
  'cookie-policy': { eyebrow: 'Boutique information', title: 'Cookie policy', lead: 'This placeholder must be replaced with an approved cookie policy before public launch.', sections: [{ title: 'Browser storage', body: 'Local browser storage is used only for guest fallback data and account-specific offline cache support.' }] }
};

export const StaticPage: React.FC<{ view: AppView }> = ({ view }) => {
  const { navigate } = useStore();
  const page = pages[view];
  if (!page) return null;
  return <main className="min-h-[65vh] bg-[#fffdf9] px-4 py-14 sm:px-7 sm:py-20"><article className="mx-auto max-w-3xl"><p className="text-[10px] uppercase tracking-[.2em] text-stone-500">{page.eyebrow}</p><h1 className="mt-3 font-serif text-5xl">{page.title}</h1><p className="mt-6 text-lg leading-8 text-stone-600">{page.lead}</p><div className="mt-12 space-y-8 border-t border-[#ddd7cf] pt-8">{page.sections.map((section) => <section key={section.title}><h2 className="font-serif text-3xl">{section.title}</h2><p className="mt-3 leading-7 text-stone-600">{section.body}</p></section>)}</div><button onClick={() => navigate('contact')} className="mt-10 border border-[#2c2926] px-6 py-3 text-[11px] font-semibold uppercase tracking-[.12em]">Contact the concierge</button></article></main>;
};

export const NotFoundPage: React.FC = () => { const { navigate } = useStore(); return <main className="grid min-h-[65vh] place-items-center bg-[#fffdf9] px-5 text-center"><div><p className="text-[10px] uppercase tracking-[.2em] text-stone-500">404</p><h1 className="mt-4 max-w-xl font-serif text-4xl sm:text-6xl">The piece you’re looking for could not be found.</h1><div className="mt-8 flex flex-wrap justify-center gap-3"><button onClick={() => navigate('home')} className="bg-[#2c2926] px-6 py-3 text-[11px] font-semibold uppercase tracking-[.12em] text-white">Return home</button><button onClick={() => navigate('shop')} className="border border-[#2c2926] px-6 py-3 text-[11px] font-semibold uppercase tracking-[.12em]">Explore collections</button></div></div></main>; };
