import React from 'react';
import { MapPin, Mail, Phone } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { BrandMark } from '../../config/brand';

export const Footer: React.FC = () => {
  const { navigate, setFilters, cms } = useStore();
  const goToNewArrivals = () => { setFilters((current) => ({ ...current, category: 'All', sortBy: 'newest', searchQuery: '' })); navigate('shop'); };
  const Link = ({ view, children }: { view: Parameters<typeof navigate>[0]; children: React.ReactNode }) => <button onClick={() => navigate(view)} className="text-left text-xs leading-5 text-stone-300 transition hover:text-white">{children}</button>;
  const contact = cms.contact;
  return <footer className="bg-[#272421] text-[#fffdf9]"><div className="mx-auto grid max-w-[1440px] gap-x-8 gap-y-10 px-4 py-14 sm:px-7 lg:grid-cols-[1.45fr_.7fr_.9fr_.7fr_1.3fr] lg:py-16"><section><BrandMark inverse /><p className="mt-5 max-w-sm text-sm leading-6 text-stone-300">{cms.content.footerDescription}</p></section><section className="space-y-3"><h2 className="text-[10px] font-semibold uppercase tracking-[.18em] text-stone-100">Shop</h2><div className="grid gap-2"><Link view="shop">Shop</Link><button onClick={() => navigate('shop')} className="text-left text-xs leading-5 text-stone-300 transition hover:text-white">Collections</button><button onClick={goToNewArrivals} className="text-left text-xs leading-5 text-stone-300 transition hover:text-white">New Arrivals</button></div></section><section className="space-y-3"><h2 className="text-[10px] font-semibold uppercase tracking-[.18em] text-stone-100">Customer Care</h2><div className="grid gap-2"><Link view="contact">Contact</Link><Link view="shipping-policy">Shipping</Link><Link view="returns-policy">Returns</Link><Link view="order-tracking">Order Tracking</Link><Link view="tailoring-guide">Size Guide</Link></div></section><section className="space-y-3"><h2 className="text-[10px] font-semibold uppercase tracking-[.18em] text-stone-100">Company</h2><div className="grid gap-2"><Link view="about">About Us</Link><Link view="privacy-policy">Privacy</Link><Link view="terms-policy">Terms</Link></div></section><section className="space-y-3"><h2 className="text-[10px] font-semibold uppercase tracking-[.18em] text-stone-100">Contact</h2><div className="grid gap-3 text-xs leading-5 text-stone-300"><a className="flex items-start gap-2 transition hover:text-white" href={contact.mapsUrl} target="_blank" rel="noreferrer"><MapPin className="mt-0.5 h-4 w-4 shrink-0" /><span>{contact.addressLines.slice(0, 4).join(', ')}</span></a><a className="flex items-center gap-2 transition hover:text-white" href={contact.whatsappUrl} target="_blank" rel="noreferrer"><Phone className="h-4 w-4 shrink-0" />{contact.phone}</a><a className="flex items-center gap-2 break-all transition hover:text-white" href={`mailto:${contact.email}`}><Mail className="h-4 w-4 shrink-0" />{contact.email}</a><a href={contact.mapsUrl} target="_blank" rel="noreferrer" className="mt-1 w-fit border-b border-stone-400 pb-0.5 text-[10px] font-semibold uppercase tracking-[.12em] text-stone-100 transition hover:border-white hover:text-white">Google Maps</a></div></section></div><div className="border-t border-stone-700"><div className="mx-auto flex max-w-[1440px] px-4 py-5 text-[11px] text-stone-400 sm:px-7"><span>© 2026 AB Collection. All rights reserved.</span></div></div></footer>;
};
