import React, { useMemo, useState } from 'react';
import { ArrowRight, Mail } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { HeroBanner } from './HeroBanner';
import { FeaturedGrid } from './FeaturedGrid';
import { CustomTailoringBanner } from './CustomTailoringBanner';

export const StorefrontHomePage: React.FC = () => {
  const { products, navigate, setFilters, showToast } = useStore();
  const [email, setEmail] = useState('');
  const categories = useMemo(() => [...new Set(products.map((product) => product.category))].filter(Boolean).slice(0, 6), [products]);
  const selectCategory = (category: string) => { setFilters((current) => ({ ...current, category, searchQuery: '' })); navigate('shop'); };
  const subscribe = (event: React.FormEvent) => { event.preventDefault(); showToast('Thanks for your interest', 'Newsletter delivery is not configured yet.', 'info'); setEmail(''); };
  return <><HeroBanner /><FeaturedGrid /><section className="border-y border-[#ddd7cf] bg-[#f7f5f2]"><div className="mx-auto max-w-[1440px] px-4 py-16 sm:px-7 sm:py-24"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-stone-500">Shop by category</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Explore the collections</h2><p className="mt-3 max-w-xl text-sm leading-6 text-stone-600">Categories are driven by the catalog and can grow as AB Collection adds products.</p><div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <button key={category} onClick={() => selectCategory(category)} className="group min-h-56 border border-[#ddd7cf] bg-white p-6 text-left transition hover:border-[#2c2926]"><p className="text-[10px] uppercase tracking-[.17em] text-stone-500">{products.filter((item) => item.category === category).length} products</p><h3 className="mt-10 font-serif text-3xl">{category}</h3><span className="mt-5 inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.12em]">View collection <ArrowRight className="h-3.5 w-3.5" /></span></button>)}</div>{!categories.length && <p className="mt-8 text-sm text-stone-600">Collections will appear here when products are published.</p>}</div></section><CustomTailoringBanner /><section className="border-t border-[#ddd7cf] bg-[#2c2926] px-4 py-16 text-[#fffdf9] sm:px-7 sm:py-24"><div className="mx-auto grid max-w-[920px] gap-8 text-center"><div><p className="text-[10px] uppercase tracking-[.24em] text-[#d8c8b7]">AB Collection updates</p><h2 className="mt-3 font-serif text-4xl sm:text-5xl">Stay in the know.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 text-stone-300">Newsletter delivery is not connected in this build.</p></div><form onSubmit={subscribe} className="mx-auto flex w-full max-w-xl flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="home-newsletter">Email address</label><div className="relative flex-1"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" /><input id="home-newsletter" value={email} onChange={(event) => setEmail(event.target.value)} type="email" required placeholder="Your email address" className="w-full border border-white/30 bg-transparent py-3.5 pl-11 pr-4 text-sm text-white placeholder:text-stone-400" /></div><button className="bg-[#fffdf9] px-6 py-3.5 text-[11px] font-semibold uppercase tracking-[.12em] text-[#2c2926]">Join the list</button></form></div></section></>;
};
