import React from 'react';
import { ArrowRight, Heart } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { Category } from '../../types';

const categories: { label: string; category: Category; image: string }[] = [
  { label: 'Silk Sarees', category: 'Kanjeevaram Silks', image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80' },
  { label: 'Evening Edit', category: 'Designer Sarees', image: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=900&q=80' },
  { label: 'Bridal Couture', category: 'Bridal Lehengas', image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=900&q=80' },
  { label: 'Temple Jewellery', category: 'Temple Jewelry', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80' }
];

export const StorefrontHomePage: React.FC = () => {
  const { products, navigate, setFilters, formatPrice, toggleWishlist, isInWishlist } = useStore();
  const selectCategory = (category: Category) => { setFilters((current) => ({ ...current, category, searchQuery: '' })); navigate('shop'); };
  const featured = products.slice(0, 4);
  return <div className="bg-[#fffdf9] text-[#2c2926]">
    <section className="mx-auto grid max-w-[1440px] border-x border-[#e3ddd6] lg:grid-cols-[1.15fr_.85fr]">
      <div className="relative min-h-[480px] overflow-hidden bg-stone-200 sm:min-h-[620px]"><img src="https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1600&q=85" alt="Miyapur silk collection" className="absolute inset-0 h-full w-full object-cover object-top" /><div className="absolute inset-0 bg-black/25" /><div className="relative flex h-full min-h-[480px] max-w-xl flex-col justify-end p-8 text-white sm:min-h-[620px] sm:p-14"><p className="text-[10px] uppercase tracking-[.26em]">Autumn / Winter collection</p><h1 className="mt-4 max-w-md font-serif text-4xl leading-[.94] sm:text-6xl">Timeless Elegance.<br />Modern Grace.</h1><button onClick={() => selectCategory('Designer Sarees')} className="mt-7 flex w-fit items-center gap-2 border border-white bg-white/10 px-5 py-3 text-xs font-semibold uppercase tracking-widest backdrop-blur hover:bg-white hover:text-stone-900">Explore the edit <ArrowRight className="h-3.5 w-3.5" /></button></div></div>
      <div className="grid grid-cols-2 bg-[#f5f1ec] p-3 sm:p-5"><div className="col-span-2 flex flex-col justify-center p-5 sm:p-9"><p className="text-[10px] uppercase tracking-[.2em] text-stone-500">Miyapur Boutique</p><h2 className="mt-2 font-serif text-3xl sm:text-4xl">Quietly considered. Beautifully made.</h2><p className="mt-3 max-w-md text-xs leading-6 text-stone-600">Heritage textiles, contemporary silhouettes and personal tailoring for the moments you want to keep.</p></div>{categories.map((item) => <button key={item.label} onClick={() => selectCategory(item.category)} className="group relative aspect-square overflow-hidden border border-[#f5f1ec] text-left"><img src={item.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 px-4 py-3 text-xs text-white">{item.label}</span></button>)}</div>
    </section>
    <section className="mx-auto max-w-[1440px] px-4 py-16 sm:px-7"><div className="flex items-end justify-between border-b border-[#ddd7cf] pb-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-stone-500">The New Collection</p><h2 className="mt-2 font-serif text-3xl">Modern heirlooms</h2></div><button onClick={() => navigate('shop')} className="text-xs underline underline-offset-4">Shop all</button></div><div className="grid grid-cols-2 gap-x-4 gap-y-9 pt-7 sm:grid-cols-4">{featured.map((product) => <article key={product.id} className="group relative"><button onClick={() => navigate('product-detail', product.id)} className="block w-full text-left"><div className="relative aspect-[3/4] overflow-hidden bg-[#f2eee8]"><img src={product.images[0]} alt={product.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" />{product.isNewArrival && <span className="absolute left-2 top-2 bg-[#fffdf9] px-2 py-1 text-[9px] uppercase tracking-wider">New</span>}</div><h3 className="mt-3 truncate text-xs font-medium">{product.title}</h3><p className="mt-1 text-xs text-stone-500">{formatPrice(product.priceINR)}</p></button><button onClick={() => toggleWishlist(product.id)} className="absolute right-2 top-2 bg-white p-2" aria-label="Save to wishlist"><Heart className={`h-3.5 w-3.5 ${isInWishlist(product.id) ? 'fill-[#625e59] text-[#625e59]' : ''}`} /></button></article>)}</div></section>
    <section className="border-y border-[#ddd7cf] bg-[#ebe7e1]"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-12 sm:grid-cols-3 sm:px-7"><div><p className="font-serif text-2xl">Personal styling</p><p className="mt-2 text-xs leading-5 text-stone-600">Private appointments, virtual consultations and thoughtful assistance from our atelier.</p></div><div><p className="font-serif text-2xl">Made for you</p><p className="mt-2 text-xs leading-5 text-stone-600">Custom blouse tailoring and alterations guided by your measurement vault.</p></div><div><button onClick={() => navigate('contact')} className="mt-2 border border-[#625e59] px-5 py-3 text-xs font-semibold uppercase tracking-widest">Book an appointment</button></div></div></section>
  </div>;
};
