import assert from 'node:assert/strict';
import { initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { PaymentService } from '../server/payments/service.js';
import { parseCheckout } from '../server/payments/validation.js';
import type { PaymentProvider, ProviderOrder } from '../server/payments/provider.js';
import { fulfilOrder } from '../server/orders/fulfil.js';
assert.equal(process.env.FIRESTORE_EMULATOR_HOST, '127.0.0.1:8189', 'Local emulator only');
const db = getFirestore(initializeApp({ projectId: 'demo-ab-payments' }, 'payment-tests'));
const product = { id: 'emulator-dress', title: 'Dress', sku: 'EM1', priceINR: 1499, stockCount: 1, colors: [], availableSizes: [], customStitchingAvailable: false, customStitchingFeeINR: 0 };
await db.doc('products/emulator-dress').set({ data: product, status: 'active', inventoryVersion: 0 });
await db.doc('settings/admin').set({ data: { checkoutCharges: [] } });
const orders: ProviderOrder[] = []; let captured = false; let now = Date.now();
const provider: PaymentProvider = { keyId: 'mock-emulator-public', createOrder: async (amount, receipt, checkoutId) => { const result = { id: 'order_emulator', amount, receipt, currency: 'INR', notes: { checkoutId } }; orders.push(result); return result; }, order: async () => orders[0], findOrders: async () => orders, payment: async () => ({ id: 'pay_emulator', order_id: 'order_emulator', amount: 149900, currency: 'INR', captured, status: captured ? 'captured' : 'created', amount_refunded: 0 }), payments: async () => captured ? [await provider.payment('pay_emulator')] : [], refunds: async () => [] };
const service = new PaymentService(db, provider, () => now);
const request = parseCheckout({ intentId: 'emulator-intent-123', items: [{ productId: 'emulator-dress', quantity: 1 }], shippingAddress: { fullName: 'Emulator Customer', phone: '9999999999', email: 'emulator@example.com', addressLine1: 'Test street', city: 'Hyderabad', state: 'Telangana', pincode: '500001', country: 'India' } });
const concurrent = await Promise.allSettled([service.create('emulator-user-one', request), service.create('emulator-user-two', request)]);
assert.equal(concurrent.filter(r => r.status === 'fulfilled').length, 1);
const winner = concurrent.find(r => r.status === 'fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof service.create>>>;
const id = winner.value.order.id;
await assert.rejects(fulfilOrder(db, 'admin-test', id, 'Processing'), /PAYMENT_NOT_READY/);
assert.equal((await db.doc('products/emulator-dress').get()).data()!.data.stockCount, 0);
now += 900_001; await service.reconcile(id); await service.release(id);
assert.equal((await db.doc('products/emulator-dress').get()).data()!.data.stockCount, 1);
const uid = concurrent[0].status === 'fulfilled' ? 'emulator-user-one' : 'emulator-user-two';
await service.create(uid, request); assert.equal(orders.length, 1);
captured = true;
await Promise.all([service.syncPayment(id, 'pay_emulator', { id: 'same-event', hash: 'same-hash' }), service.syncPayment(id, 'pay_emulator', { id: 'same-event', hash: 'same-hash' })]);
assert.equal((await db.doc(`orders/${id}`).get()).data()!.data.paymentStatus, 'PAID');
assert.equal((await db.doc(`orders/${id}`).get()).data()!.data.timeline.length, 1);
assert.equal((await db.doc(`inventoryReservations/${id}`).get()).data()!.state, 'CONSUMED');
now += 900_001; assert.equal(await service.release(id), false);
assert.equal((await db.doc('products/emulator-dress').get()).data()!.data.stockCount, 0);
const beforeFulfilment = (await db.doc(`orders/${id}`).get()).data()!.data;
const fulfilled = await fulfilOrder(db, 'admin-test', id, 'Processing');
assert.equal(fulfilled.paymentStatus, beforeFulfilment.paymentStatus); assert.equal(fulfilled.amountPaise, beforeFulfilment.amountPaise); assert.equal(fulfilled.razorpayPaymentId, beforeFulfilment.razorpayPaymentId);
const historical = { ...beforeFulfilment, id: 'legacy-cod-emulator', paymentMethod: 'cod', paymentStatus: 'Pending' };
for (const key of ['paymentProvider', 'checkoutIntentId', 'razorpayOrderId', 'razorpayPaymentId', 'paidAt', 'paymentVerifiedAt', 'amountPaise', 'refundedAmountPaise', 'reservationExpiresAt', 'paymentReviewRequired']) delete historical[key];
await db.doc('users/legacy-customer/orders/legacy-cod-emulator').set({ customerId: 'legacy-customer', data: historical, paymentStatus: 'Pending', orderStatus: historical.orderStatus });
const old = await fulfilOrder(db, 'admin-test', 'legacy-cod-emulator', 'Processing');
assert.equal(old.paymentMethod, 'cod'); assert.equal(old.paymentStatus, 'Pending'); assert.equal(old.razorpayPaymentId, undefined);
console.log('Real Firestore emulator: stock concurrency, expiry/retry, duplicate processing, consumption and historical/admin fulfilment checks passed.');
await db.terminate();
