import React from 'react';
import { LoadingFeedback } from './Loading';

export const Skeleton = ({ className = '' }: { className?: string; key?: React.Key }) => <div aria-hidden="true" className={`bg-[#eee9e2] rounded-sm boutique-pulse ${className}`} />;
export const ProductCardSkeleton = () => <div aria-hidden="true" className="min-w-0 border border-[#ddd7cf] bg-[#fffdf9] p-2"><Skeleton className="aspect-[3/4]" /><div className="px-1 pb-1 pt-4 space-y-2"><Skeleton className="h-2.5 w-1/3" /><Skeleton className="h-4 w-4/5" /><Skeleton className="h-5 w-1/2" /><Skeleton className="h-2.5 w-1/3" /></div></div>;
export const ProductGridSkeleton = ({ count = 8, feedback = true }: { count?: number; feedback?: boolean }) => { const content = <div role="status" aria-label="Loading products" aria-busy="true" className="grid grid-cols-2 gap-x-4 gap-y-9 sm:grid-cols-3 sm:gap-x-6 xl:grid-cols-4">{Array.from({ length: count }, (_, index) => <ProductCardSkeleton key={index} />)}</div>; return feedback ? <LoadingFeedback label="Loading products...">{content}</LoadingFeedback> : content; };
export const HomeSkeleton = () => <LoadingFeedback label="Loading the boutique..."><div role="status" aria-label="Loading the boutique" aria-busy="true"><Skeleton className="h-[540px] sm:h-[590px] lg:h-[620px] xl:h-[650px]" /><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20"><div className="mb-10 flex flex-wrap items-end justify-between gap-6"><div className="w-64 space-y-3"><Skeleton className="h-3 w-1/3" /><Skeleton className="h-9 w-full" /><Skeleton className="h-4 w-4/5" /></div><div className="flex gap-2">{[0, 1, 2].map((i) => <Skeleton key={i} className="h-10 w-20 rounded-lg" />)}</div></div><ProductGridSkeleton feedback={false} /><div className="mt-20 mb-9 space-y-3"><Skeleton className="h-3 w-32" /><Skeleton className="h-10 w-64" /></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[0, 1, 2].map((i) => <Skeleton key={i} className="min-h-56" />)}</div></div></div></LoadingFeedback>;
export const DetailsSkeleton = () => <LoadingFeedback label="Loading product details..."><div role="status" aria-label="Loading details" aria-busy="true" className="mx-auto grid max-w-7xl gap-8 px-4 py-12 lg:grid-cols-2"><Skeleton className="aspect-[3/4]" /><div className="space-y-6"><Skeleton className="h-10 w-4/5" /><Skeleton className="h-6 w-1/3" /><Skeleton className="h-32 w-full" /><Skeleton className="h-12 w-full" /></div></div></LoadingFeedback>;
export function OrderSkeleton() { return <div className="space-y-5">{[0,1,2].map(i=><div key={i} className="rounded-3xl border border-[#ddd7cf] bg-white p-6 sm:p-8"><div className="flex justify-between gap-4"><Skeleton className="h-5 w-40" /><Skeleton className="h-5 w-28" /></div><div className="mt-6 flex gap-4"><Skeleton className="h-24 w-20 shrink-0" /><div className="flex-1 space-y-3"><Skeleton className="h-4 w-3/4" /><Skeleton className="h-3 w-1/3" /></div></div><Skeleton className="mt-6 h-10 w-32" /></div>)}</div>; }
export function AdminSkeleton({ dashboard = false }: { dashboard?: boolean }) { return <LoadingFeedback label="Loading store data...">{dashboard ? <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="border border-[#ddd7cf] bg-white p-4"><Skeleton className="h-3 w-2/3" /><Skeleton className="mt-4 h-9 w-1/3" /></div>)}</div> : <div className="mt-5 rounded-xl border border-[#ddd7cf] bg-white p-5"><Skeleton className="mb-6 h-5 w-2/3" />{[0,1,2,3,4].map(i=><Skeleton key={i} className="mt-4 h-14 w-full" />)}</div>}</LoadingFeedback>; }
export const PrivateLoading = ({ error, variant = 'account' }: { error?: boolean; variant?: 'account' | 'orders' | 'cart' | 'wishlist' | 'checkout' }) => error ? <div role="alert" className="px-4 py-16 text-center"><p>Your account data could not be loaded.</p><button className="mt-4 underline" onClick={() => window.location.reload()}>Retry</button></div> : <div className="mx-auto max-w-5xl space-y-6 px-4 py-12"><LoadingFeedback label={variant === 'orders' ? 'Loading your orders...' : variant === 'checkout' ? 'Loading secure checkout...' : variant === 'cart' ? 'Loading your bag...' : variant === 'wishlist' ? 'Loading your wishlist...' : 'Loading your account...'}><Skeleton className="mt-5 mb-6 h-9 w-56" />{variant === 'orders' ? <OrderSkeleton /> : variant === 'wishlist' ? <ProductGridSkeleton count={4} feedback={false} /> : variant === 'checkout' ? <div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><Skeleton className="h-96" /><Skeleton className="h-72" /></div> : [0,1,2].map(i=><Skeleton key={i} className="mt-5 h-28 w-full" />)}</LoadingFeedback></div>;
